"use client";
import React from 'react';
import { Container, Grid, Card } from '@lexforge/ui';
import { motion } from 'framer-motion';
import { useGenerationStore } from '../../store/useGenerationStore';
import { ResultCard } from './ResultCard';

const showcaseNames = [
  { name: 'Vora', meaning: 'Vorare (Latin)', context: 'Appetite, Speed' },
  { name: 'Axiom', meaning: 'Axioma (Greek)', context: 'Foundation, Truth' },
  { name: 'Syntra', meaning: 'Synthesis (Greek)', context: 'Combining, Future' },
  { name: 'Velora', meaning: 'Velox (Latin)', context: 'Velocity, Elegance' },
  { name: 'Altis', meaning: 'Altus (Latin)', context: 'Height, Peak' },
  { name: 'Nexa', meaning: 'Nexus (Latin)', context: 'Connection, Hub' },
];

export const GeneratedNamesShowcase = () => {
  const { results, fsmState } = useGenerationStore();
  const isLoading = fsmState === 'VALIDATING' || fsmState === 'GENERATING' || fsmState === 'STREAMING';

  return (
    <section className="py-32 bg-white/40 backdrop-blur-md border-y border-slate-200/60 min-h-screen" id="showcase">
      <Container>
        <div className="mb-20 text-center max-w-2xl mx-auto">
          <motion.h2 
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true, margin: "-100px" }}
            transition={{ duration: 0.6, ease: [0.16, 1, 0.3, 1] }}
            className="text-[32px] font-serif font-semibold mb-4 text-slate-900 tracking-tight"
          >
            {results.length > 0 ? 'Forged Identities' : 'Curated Outputs'}
          </motion.h2>
          <motion.p
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true, margin: "-100px" }}
            transition={{ duration: 0.6, delay: 0.1, ease: [0.16, 1, 0.3, 1] }}
            className="text-slate-600 text-base leading-relaxed"
          >
            {results.length > 0 ? 'Live results generated by the LexForge engine.' : 'A sample of phonetically balanced, semantically rooted brand names.'}
          </motion.p>
        </div>
        
        {isLoading && results.length === 0 ? (
          <Grid cols={1} gap={8} className="md:grid-cols-2 lg:grid-cols-3">
            {[1, 2, 3, 4, 5, 6].map(i => (
              <div key={i} className="h-64 rounded-2xl border border-slate-100 p-6 bg-slate-50">
                <div className="flex flex-col gap-4 h-full">
                  <div className="h-8 w-3/4 bg-slate-200 animate-pulse rounded" />
                  <div className="h-4 w-1/2 bg-slate-200 animate-pulse rounded" />
                  <div className="pt-4 space-y-2 mt-auto">
                    <div className="h-3 w-1/4 bg-slate-200 animate-pulse rounded" />
                    <div className="h-4 w-full bg-slate-200 animate-pulse rounded" />
                  </div>
                </div>
              </div>
            ))}
          </Grid>
        ) : results.length > 0 ? (
          <Grid cols={1} gap={8} className="md:grid-cols-2 lg:grid-cols-3">
            {results.map((result) => (
              <ResultCard key={result.name} result={result} />
            ))}
            {isLoading && (
              <div className="h-64 rounded-2xl border border-slate-100 p-6 bg-slate-50 flex items-center justify-center">
                <span className="text-sm text-slate-400 animate-pulse font-mono">Synthesizing...</span>
              </div>
            )}
          </Grid>
        ) : (
          <Grid cols={1} gap={8} className="md:grid-cols-2 lg:grid-cols-3">
            {showcaseNames.map((item, idx) => (
              <motion.div
                key={item.name}
                initial={{ opacity: 0, y: 30 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true, margin: "-50px" }}
                transition={{ duration: 0.6, delay: idx * 0.1, ease: [0.16, 1, 0.3, 1] }}
              >
                <Card className="p-8 border border-black/5 hover:border-primary/20 hover:shadow-xl transition-all duration-300 bg-white/70 backdrop-blur-xl group cursor-default h-full">
                  <h3 className="text-4xl font-serif text-slate-900 mb-2 group-hover:text-primary transition-colors">{item.name}</h3>
                  <div className="flex justify-between items-center text-sm text-slate-500 mt-6 pt-6 border-t border-slate-100">
                    <span className="italic">{item.meaning}</span>
                    <span className="font-medium">{item.context}</span>
                  </div>
                </Card>
              </motion.div>
            ))}
          </Grid>
        )}
      </Container>
    </section>
  );
};
