import React from 'react';
import { LegalLayout } from '@/shared/ui/layouts/LegalLayout';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Terms of Service | LexForge',
};

export default function TermsOfServicePage() {
  return (
    <LegalLayout title="Terms of Service" lastUpdated="August 8, 2026">
      <h2>1. Acceptance of Terms</h2>
      <p>
        By accessing or using the LexForge service, you agree to be bound by these Terms of Service. If you disagree with any part of the terms, then you may not access the service.
      </p>

      <h2>2. Intellectual Property Rights</h2>
      <p>
        <strong>Our IP:</strong> The LexForge Engine, dataset architecture, UI design, and underlying algorithms are the exclusive property of LexForge Computational Linguistics Institute.
      </p>
      <p>
        <strong>Your IP:</strong> Any brand names, prompts, or theses generated by you using the LexForge service become your intellectual property upon generation, provided you have a Pro or Enterprise license. Free tier generations are provided under a Creative Commons (CC-BY) license.
      </p>

      <h2>3. Disclaimer of Warranties (Trademark Liability)</h2>
      <p>
        While LexForge cross-references generated names against ontological graphs to reduce trademark collisions, we DO NOT provide legal advice. LexForge makes no guarantees that a generated name is legally available for trademark registration in any jurisdiction. <strong>You are solely responsible for conducting formal trademark clearance searches through legal counsel before adopting any generated name.</strong>
      </p>

      <h2>4. Limitation of Liability</h2>
      <p>
        In no event shall LexForge, nor its directors, employees, partners, or agents, be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from your use of the generated output.
      </p>

      <h2>5. Governing Law</h2>
      <p>
        These Terms shall be governed and construed in accordance with the laws of the State of California, without regard to its conflict of law provisions.
      </p>
    </LegalLayout>
  );
}
