import fs from 'fs';
import path from 'path';

/**
 * IndexManager is responsible for loading and caching the semantic, morpheme, and ontology indexes
 * generated by the LexForge Dataset Compiler.
 * 
 * It runs exclusively on the server side to protect memory limits on the client.
 */
export class IndexManager {
  private static instance: IndexManager;
  
  private semanticIndex: Record<string, string[]> | null = null;
  private ontologyIndex: Record<string, string[]> | null = null;
  private definitionIndex: Record<string, string> | null = null;
  private isLoaded = false;
  private datasetPath = '';

  private constructor() {
    // Determine the path to the output directory of the dataset-compiler
    // In a Next.js API route, process.cwd() is usually the project root (web folder)
    this.datasetPath = path.resolve(process.cwd(), '../dataset-compiler/output');
  }

  public static getInstance(): IndexManager {
    if (!IndexManager.instance) {
      IndexManager.instance = new IndexManager();
    }
    return IndexManager.instance;
  }

  /**
   * Loads the indexes into memory if they aren't already loaded.
   */
  public async loadIndexes(): Promise<void> {
    if (this.isLoaded) return;

    try {
      const semanticPath = path.join(this.datasetPath, 'semantic-index.json');
      const ontologyPath = path.join(this.datasetPath, 'ontology-index.json');

      if (fs.existsSync(semanticPath)) {
        const raw = fs.readFileSync(semanticPath, 'utf-8');
        const parsed = JSON.parse(raw);
        this.semanticIndex = parsed.data || parsed;
      } else {
        console.warn('Semantic index not found at', semanticPath);
        this.semanticIndex = {};
      }

      if (fs.existsSync(ontologyPath)) {
        const raw = fs.readFileSync(ontologyPath, 'utf-8');
        const parsed = JSON.parse(raw);
        this.ontologyIndex = parsed.data || parsed;
      } else {
        console.warn('Ontology index not found at', ontologyPath);
        this.ontologyIndex = {};
      }

      const defPath = path.join(this.datasetPath, 'definition-index.json');
      if (fs.existsSync(defPath)) {
        const raw = fs.readFileSync(defPath, 'utf-8');
        const parsed = JSON.parse(raw);
        this.definitionIndex = parsed.data || parsed;
      } else {
        console.warn('Definition index not found at', defPath);
        this.definitionIndex = {};
      }

      this.isLoaded = true;
      console.log(`[IndexManager] Successfully loaded indexes into memory.`);
    } catch (e) {
      console.error('[IndexManager] Failed to load indexes:', e);
      throw e;
    }
  }

  public getSemanticIndex(): Record<string, string[]> {
    if (!this.isLoaded) throw new Error('Indexes not loaded. Call loadIndexes() first.');
    return this.semanticIndex || {};
  }

  public getOntologyIndex(): Record<string, string[]> {
    if (!this.isLoaded) throw new Error('Indexes not loaded. Call loadIndexes() first.');
    return this.ontologyIndex || {};
  }

  public getDefinitionIndex(): Record<string, string> {
    if (!this.isLoaded) throw new Error('Indexes not loaded. Call loadIndexes() first.');
    return this.definitionIndex || {};
  }
}
