import { ScoredCandidate } from './ScoringEngine';
import { GenerationContext } from '../context/GenerationContext';

export type RankedCandidate = ScoredCandidate;

export class RankingEngine {
  public rank(candidates: ScoredCandidate[], context: GenerationContext): RankedCandidate[] {
    // Ranking engine NEVER calculates scores, it only sorts by the confidence score
    // generated by the ScoringEngine.
    const ranked = [...candidates];
    ranked.sort((a, b) => (b.score?.totalScore || 0) - (a.score?.totalScore || 0));
    return ranked;
  }
}
