import React from 'react';
import { LegalLayout } from '@/shared/ui/layouts/LegalLayout';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Privacy Policy | LexForge',
};

export default function PrivacyPolicyPage() {
  return (
    <LegalLayout title="Privacy Policy" lastUpdated="August 8, 2026">
      <h2>1. Introduction</h2>
      <p>
        At LexForge Computational Linguistics Institute ("LexForge", "we", "us", or "our"), we are committed to protecting your privacy. This Privacy Policy explains how we collect, use, and safeguard your information when you visit our website or use our generative linguistic services.
      </p>

      <h2>2. Information We Collect</h2>
      <p>We may collect the following types of information:</p>
      <ul>
        <li><strong>Personal Data:</strong> Name, email address, and billing information when you create an account or subscribe to a paid tier.</li>
        <li><strong>Usage Data:</strong> Brand theses, generated prompts, and the output generated by our engine. This data is used to improve our models unless you opt out.</li>
        <li><strong>Technical Data:</strong> IP addresses, browser types, and usage metrics collected via standard web analytics.</li>
      </ul>

      <h2>3. How We Use Your Information</h2>
      <p>We use the collected data to:</p>
      <ul>
        <li>Provide, maintain, and improve the LexForge Engine.</li>
        <li>Process your transactions and manage your subscription.</li>
        <li>Understand how users interact with our linguistic models to refine our node generation algorithms.</li>
        <li>Communicate with you regarding updates, security alerts, and support messages.</li>
      </ul>

      <h2>4. Data Security</h2>
      <p>
        We implement enterprise-grade security measures to protect your personal and proprietary generation data. All generated brand data for Pro and Enterprise users is encrypted at rest and in transit.
      </p>

      <h2>5. Contact Us</h2>
      <p>
        If you have questions about this Privacy Policy, please contact us at privacy@lexforge.com.
      </p>
    </LegalLayout>
  );
}
