import React from 'react';
import { LegalLayout } from '@/shared/ui/layouts/LegalLayout';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Trademark Disclaimer | LexForge',
};

export default function DisclaimerPage() {
  return (
    <LegalLayout title="Trademark Disclaimer" lastUpdated="August 8, 2026">
      <h2>1. Not Legal Advice</h2>
      <p>
        The information and output provided by LexForge is for informational and creative purposes only and does not constitute legal advice. LexForge is an algorithmic generation engine, not a law firm.
      </p>

      <h2>2. Trademark Clearance</h2>
      <p>
        While LexForge attempts to filter out known trademarks using ontological graphs, <strong>we do not guarantee that any name generated by our platform is legally available for use in commerce or registerable as a trademark.</strong>
      </p>
      <p>
        Before investing resources into a brand identity, you must conduct a comprehensive trademark search and consult with a qualified trademark attorney in your specific jurisdiction. LexForge bears no responsibility for legal challenges, cease and desist letters, or trademark infringement lawsuits arising from the use of names generated on our platform.
      </p>
    </LegalLayout>
  );
}
